# Generated by Django 5.1 on 2026-09-22 00:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AfricanDish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_id', models.SlugField(max_length=120, unique=True)),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('origin', models.CharField(default='West Africa', max_length=150)),
                ('category', models.CharField(choices=[('Soups & Stews', 'Soups & Stews'), ('Rice Dishes', 'Rice Dishes'), ('Swallows', 'Swallows'), ('Pastries & Snacks', 'Pastries & Snacks'), ('Grilled & Smoked', 'Grilled & Smoked'), ('Bean Delicacies', 'Bean Delicacies'), ('Breakfast & Porridge', 'Breakfast & Porridge'), ('Beverages', 'Beverages'), ('International Classics', 'International Classics')], default='Soups & Stews', max_length=100)),
                ('difficulty', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], default='Medium', max_length=50)),
                ('prep_time_mins', models.PositiveIntegerField(default=20)),
                ('cook_time_mins', models.PositiveIntegerField(default=45)),
                ('servings', models.PositiveIntegerField(default=4)),
                ('calories', models.PositiveIntegerField(default=450)),
                ('protein_g', models.FloatField(default=22.0)),
                ('carbs_g', models.FloatField(default=45.0)),
                ('fat_g', models.FloatField(default=16.0)),
                ('fiber_g', models.FloatField(default=5.0)),
                ('image_url', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('visual_hallmarks', models.JSONField(blank=True, default=list, help_text='Distinctive visual traits for CV detection')),
                ('ingredients', models.JSONField(default=list, help_text='Structured list of ingredients and measures')),
                ('instructions', models.JSONField(default=list, help_text='Step-by-step culinary preparation instructions')),
                ('culinary_tips', models.JSONField(blank=True, default=list, help_text='Chef advice for optimal flavor')),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Culinary Dish',
                'verbose_name_plural': 'Culinary Dishes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FoodScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='scans/%Y/%m/')),
                ('image_data', models.TextField(blank=True, help_text='Data URL or preview URL')),
                ('predicted_name', models.CharField(max_length=200)),
                ('confidence', models.FloatField(default=0.0, help_text='Prediction confidence percentage (0-100)')),
                ('detected_cues', models.JSONField(blank=True, default=list)),
                ('visible_ingredients', models.JSONField(blank=True, default=list)),
                ('alternative_candidates', models.JSONField(blank=True, default=list)),
                ('detection_engine', models.CharField(choices=[('hybrid_vision', 'Hybrid Color-Texture ML Engine'), ('gemini_vision', 'Gemini Multimodal Vision API'), ('manual_match', 'Manual Recipe Selection')], default='hybrid_vision', max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('predicted_dish', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scans', to='foodsnap_api.africandish')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Food Scan Inference',
                'verbose_name_plural': 'Food Scan Inferences',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('displayName', models.CharField(blank=True, max_length=150)),
                ('dietary_preferences', models.JSONField(blank=True, default=list)),
                ('skill_level', models.CharField(default='Home Chef', max_length=50)),
                ('bio', models.TextField(blank=True)),
                ('avatar_url', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='foodsnap_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FavoriteRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='foodsnap_api.africandish')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foodsnap_favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Favorite Recipe',
                'verbose_name_plural': 'Favorite Recipes',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'dish')},
            },
        ),
    ]
